spring:
  datasource:
    driver-class-name: org.h2.Driver  # H2 데이터베이스를 사용하기 위한 JDBC 드라이버 클래스 이름
    username: sa                     # 데이터베이스 접속 사용자 이름 (기본값: 'sa')
    password:                        # 데이터베이스 접속 비밀번호 (H2의 기본값은 빈값)
    url: jdbc:h2:mem:test         # 데이터베이스 URL (H2 메모리 모드로 'test' 이름의 DB 생성)
  h2:
    console:
      enabled: true                  # H2 웹 콘솔 활성화 (true로 설정 시, 웹 UI를 통해 DB 확인 가능)
      path: /h2-console              # H2 콘솔에 접속할 경로 (예: http://localhost:<port>/h2-console)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # JPA에서 사용할 데이터베이스 방언(H2 DB에 맞게 설정)
    hibernate:
      ddl-auto: create        # 데이터베이스 초기화 전략

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Hibernate에 사용할 H2 데이터베이스 방언
        format_sql: true      # true 설정 시, 출력되는 SQL 쿼리를 포맷팅하여 가독성 향상
        show_sql: true        # true 설정 시, 실행되는 SQL 쿼리를 콘솔에 출력